version: "3.7"

services:

  database:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendance
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    container_name: backend
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - transcendance

  frontend-vite:
    container_name: frontend-vite
    depends_on:
      - database
      - backend
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    ports:
      - 443:443

networks:
  transcendance:
    driver: bridge

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      device: './data'
      o: bind

# ADD MEILISEARCH
