version: "3.1"

services:
  database:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ../backend/.env
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  # frontend:
  #   driver: bridge
  backend:
    driver: bridge
