name: Compilingtest
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: cd frontend && npm install && npm start
