name: Compilingtest
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '12.x'
      - name: Check Compile Status
        run: cd frontend && npm install && npm start
